# Generated by Django 3.2 on 2021-05-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DairyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
